CREATE TABLE PRODUTOS
(
NOME VARCHAR(200) NOT NULL,
DESCRICAO VARCHAR(200) NOT NULL,
AVALIACAO INTEGER,
SKU INTEGER NOT NULL,
PRECO DECIMAL 10,2 NOT NULL,
PRIMARY KEY (SKU)
);

INSERT INTO PRODUTOS(NOME, DESCRICAO, AVALIACAO, SKU, PRECO)
VALUES ()
